services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: banco
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my_network

  microservicio-clientes:
    build: ../WSClientes
    container_name: clientes-servicio
    networks:
      - my_network
    environment:
      - TZ=America/Lima
    ports:
      - "8081:8080"  # Exponer puerto 8081 en localhost
    depends_on:
      - mysql-db

  microservicio-cuentas:
    build: ../WSCuentas
    container_name: cuentas-servicio
    networks:
      - my_network
    environment:
      - TZ=America/Lima
      - WS_CLIENTES_URL=http://microservicio-clientes:8080  # URL del servicio WSClientes
    ports:
      - "8082:8080"  # Exponer puerto 8082 en localhost
    depends_on:
      - mysql-db
networks:
  my_network:
    driver: bridge

volumes:
  mysql_data: